// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-3')['BButton']
    BDropdown: typeof import('bootstrap-vue-3')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-3')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-3')['BForm']
    BFormGroup: typeof import('bootstrap-vue-3')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-3')['BFormInput']
    BModal: typeof import('bootstrap-vue-3')['BModal']
    BPagination: typeof import('bootstrap-vue-3')['BPagination']
    BTable: typeof import('bootstrap-vue-3')['BTable']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
